#! /usr/bin/env python
# encoding: utf-8


def options(self):
    pass

def configure(self):
    #audiolib include path
    pass

def build(self):
    self.program(
        source = self.path.ant_glob('*.cpp'),
        includes = self.include_dirs(),
        target = 'app',
        use = ['audiolib'],
        )
