#! /usr/bin/env python
# encoding: utf-8


def options(opt):
    pass

def configure(conf):
    #audiolib include path
    pass

def build(bld):
    bld.program(
        source = bld.path.ant_glob('src/main.cpp'),
        target = 'app',
        use = ['audiolib'],
        )
