#! /usr/bin/env python
# encoding: utf-8

def options(opt):
    opt.recurse('audiolib')
    opt.recurse('main')

def configure(conf):
    conf.recurse('audiolib')
    conf.recurse('main')

def build(bld):
    bld.recurse('audiolib')
    bld.recurse('main')
